### ISSUE TITLE
Questions about Attachment acf data in Gallery Field

### ISSUE THREAD

**Issue by fionaleews** [airesvsg/acf-to-wp-rest-api#1]
HI folk!
thanks for making this great plugin!
i have a question about showing [attachment] custom field data in the gallery field in post by wp-json.

The custom field [media_docu_scource]& [media_docu_description]I made in Attachment  could not be shown in the ACF gallery field, which i made the gallery field in post.

Please see the attached image below 
![how-to-insert-galleryfield](https://cloud.githubusercontent.com/assets/14248718/9831733/ca3bf372-5994-11e5-89ef-e3baa9cbeb16.jpg)

Do you know any method for solving this problem ?

thanks a lot!

**Comment by airesvsg** [comment]
Hi, 
you can use the filter **acf_to_wp_rest_api_***{type}***_data**

The wildcard *{type}* can be: post | user | term | comment | attachment

How to use:

```php
add_filter( 'acf_to_wp_rest_api_post_data', function( $data ) {
	if ( isset( $data['type'] ) && 'my_custom_post_type' == $data['type'] && isset( $data['acf'] ) ) {
		if ( isset( $data['acf']['my_field_name'] ) && is_array( $data['acf']['my_field_name'] ) && ! empty( $data['acf']['my_field_name'] ) ) {
			foreach ( $data['acf']['my_field_name'] as &$item ) {
				$item['acf_attachment'] = get_fields( $item['id'] );
			}
		}
	}
	return $data;
}, 10, 3 );
```

**Comment by fionaleews** [comment]
Hi!
thanks so much for reply!
where should i add this filter? 
in the functions.php in my themes' folder or anywhere else??

would u please explain more should i hv to change $data['type'] & 'my_custom_post_type' & my_field_name' ?

thanks so much!

**Comment by airesvsg** [comment]
Hi,
you should add this snippet in your *functions.php*.

according to the image above:
my_custom_post_type = **image**
my_field_name = **point_1930_gallery**

**Comment by fionaleews** [comment]
Thanks a lot for the reply!
Yeah! it works!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Save my life!!

thanks!

**Comment by airesvsg** [comment]
:smile: :+1:
