### ISSUE TITLE
Rename from 'acf' in response

### ISSUE THREAD

**Issue by misfist** [airesvsg/acf-to-wp-rest-api#11]
I temporary need to use v1 of the REST API and would like to change `acf` to something else (say, `custom_fields`). Your explanation for v2 (https://github.com/airesvsg/acf-to-rest-api/issues/41) worked exactly as expected. So, I tried to do something similar in v1 using the `acf_to_wp_rest_api_{$this->type}_data` filter.

But, I wasn't able to get it to work. 

``` php
apply_filters( "acf_to_wp_rest_api_{$this->type}_data", $data, $object, $context );
```

Any guidance would be appreciated.

**Comment by airesvsg** [comment]
Hi @misfist,
please try it:
```PHP
add_filter( 'acf_to_wp_rest_api_{type}_data', function( $data ) {
    if ( isset( $data['acf'] ) ) {
      $data['custom_fields'] = $data['acf'];
      unset( $data['acf'] );
    }

    return $data;
}, 10 );
```
The wildcard `{type}` can be: post | user | term | comment | attachment | options

Thanks

**Comment by misfist** [comment]
Thank you! I really appreciate you getting back to me! It worked exactly has I wanted.
