### ISSUE TITLE
Orderby ACF field

### ISSUE THREAD

**Issue by earnest-dev** [airesvsg/acf-to-wp-rest-api#12]
Hello,

Thanks for the plugin, I've got great use out of it.
However, I'm stuck with one particular issue, which I cannot find a resolution to anywhere, hopefully you can help.

I have a custom post type 'projects' & an ACF field 'client'.
I want to make a JSON call which will return my projects ordered by client alphabetically.

I have am trying the following URL: "/wp-json/wp/v2/projects?meta_key=client&filter[orderby]=meta_value_num"

I imagine there is some code that will ned to go into my functions.php file, but I cannot find what it will need to be. I appreciate your help.

Many thanks,
Jack.

**Comment by airesvsg** [comment]
Hi @earnest-dev,
please update your plugin to new version.
https://github.com/airesvsg/acf-to-rest-api

Thanks

**Comment by earnest-dev** [comment]
Hi,

Thanks for getting back to me so quickly. I have updated the plugin as well as all other plugins, but still not seeing the desired result.

Is there any code I need to add to functions.php or anywhere else?

Thanks.

**Comment by airesvsg** [comment]
Try it: `/wp-json/wp/v2/projects??filter[orderby]=client`

Thanks

**Comment by earnest-dev** [comment]
Hi,

Thanks for the response, unfortunately I am still not seeing the desired result.
Is there anything else I can try?

Thanks.

**Comment by airesvsg** [comment]
Hi,
Please watch my test.
https://www.youtube.com/watch?v=8oZbtlWz6f4

Thanks

**Comment by earnest-dev** [comment]
Thanks again for the quick response.

Using the following URL:
http://localhost:8888/earnest/wp-json/wp/v2/projects?filter[orderby]=client&filter[order]=asc

Changing "asc" for "desc" reverses the order of the projects, however neither order is alphabetical by client, they are just sorted by date.

Many thanks.

**Comment by airesvsg** [comment]
you need to set an order.

**Comment by earnest-dev** [comment]
Hi,

I'm using this URL, which has a filter **filter[order]=asc** on the end:

.../wp-json/wp/v2/projects?filter[orderby]=client&filter[order]=asc

But it is still not ordering by client as I was hoping for.

Is there anything else I can try? Do I need to add anything to my functions.php file?

I appreciate the help.
Thanks.

**Comment by airesvsg** [comment]
Hi @earnest-dev,
Can you send me the database dump? 
airesvsg@gmail.com

Thanks

**Comment by earnest-dev** [comment]
Yes, will do.

Thanks

**Comment by spharrychuang** [comment]
> you need to set an order.

Cool, ~ is this filter[orderby] support ACF V3?

**Comment by brunodeangelis** [comment]
> Hi,
> Please watch my test.
> https://www.youtube.com/watch?v=8oZbtlWz6f4
> 
> Thanks

Unfortunately this is not working for me. I'm using version 3.3.1

Any help is greatly appreciated!
