### ISSUE TITLE
Retrieving ACFs from custom Option Pages

### ISSUE THREAD

**Issue by rdlmda** [airesvsg/acf-to-wp-rest-api#14]
I'm using ACF's `acf_add_options_page()` and `acf_add_options_sub_page()` to create option pages and subpages, and I can't find a way of retrieving these fields on the REST API.

I've registered one page with two subpages:

```
add_action('init','register_option_pages');
function register_option_pages() {

  if( function_exists('acf_add_options_page') ) {

    acf_add_options_page(array(
      'page_title' 	=> 'Apresentação do Projeto',
      'menu_slug' 	=> 'apresentacao',
      'capability'	=> 'edit_posts',
      'position' => 5.7,
    ));

    acf_add_options_sub_page(array(
      'page_title' 	=> 'Sobre',
      'parent_slug'	=> 'apresentacao',
    ));

    acf_add_options_sub_page(array(
      'page_title' 	=> 'Estrutura',
      'parent_slug'	=> 'apresentacao',
    ));

  }
}
```

There's content on the fields, but nothing shows up on the REST API.

I noticed there's a `/acf/v3/options/(?P<id>[\w\-\_]+)/?(?P<field>[\w\-\_]+)?` route described on the `/acf/v3/` endpoint, so I tried the following routes, with no succes:

- `/acf/v3/options/`: returns `404`.
- `/acf/v3/options/apresentacao`: returns `{"acf":[]}`.
- `/acf/v3/options/apresentacao/sobre`: returns `{"sobre":null}`.
- `/acf/v3/options/acf-options-sobre`: returns `{"acf":[]}`

How should I proceed?

**Comment by airesvsg** [comment]
Hi @rdlmda,

I'm not give support for this version, please update to v3.

https://github.com/airesvsg/acf-to-rest-api

The link below may help you.
https://github.com/airesvsg/acf-to-rest-api/issues/184#issuecomment-338277335

Thanks

**Comment by rdlmda** [comment]
Ooops. Somehow I missed the big "deprecated" notice on the readme.
By the way, the linked comment solves my issue, thanks!
