### ISSUE TITLE
Will this support post?

### ISSUE THREAD

**Issue by Matt2012** [airesvsg/acf-to-wp-rest-api#2]
Will this eventually let us be able to post data to acf through the wp api?

**Comment by airesvsg** [comment]
Yes, I will soon make this implementation.

**Comment by rizqinizamil** [comment]
+ 1

**Comment by airesvsg** [comment]
Hi @rizqinizamil,
I plan to launch this feature in the second week of January.

![Preview](http://airesgoncalves.com.br/screenshot/acf-to-wp-rest-api/issues/2/preview.png)

**Comment by rizqinizamil** [comment]
Wow great! Happy new year, anyway :)

**Comment by airesvsg** [comment]
:bowtie:

**Comment by EugeneLiang** [comment]
looks good! can't wait!

**Comment by airesvsg** [comment]
Hi,
I created a new repository to new version.
https://github.com/airesvsg/acf-to-rest-api

The plugin is pending approval in WordPress.org because I sent now.

Enjoy ;D

**Comment by C0mmander198** [comment]
I'm trying to get this working for a **custom post type**. I can see all ACF fields when enabling the plugin using GET - but if I switch to POST and try to create or update an existing POST I have no luck getting the custom field populated. Thoughts? Is this only working for the standard "post"? Any filter hook I have to use to implement a custom function?

**Comment by airesvsg** [comment]
Hi @C0mmander198,
You need authenticate to create or update the post, follow the link below:
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/
Thanks

**Comment by airesvsg** [comment]
**This version was discontinued, please upgrade to new version:**
https://github.com/airesvsg/acf-to-rest-api/
