### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by pnettto** [airesvsg/acf-to-wp-rest-api#3]
Hey guys, thanks for the awesome plugin, it works perfect! :)

I was just wondering if there are any plans to implement a shortcode support? Sometimes when I get fields contents the shortcodes come as they are in the database and not as compiled parts.

Many thanks once again!

**Comment by airesvsg** [comment]
Hi @brisa-pedronetto,

I don't understand very well, but you have a field in acf that the content is a shortcode?

You can use the filter, see the link https://github.com/airesvsg/acf-to-wp-rest-api/issues/1#issuecomment-139810429 or code below:

```PHP
add_filter( 'acf_to_wp_rest_api_post_data', function( $data ) {
	if ( isset( $data['type'] ) && 'my_post_type' == $data['type'] && isset( $data['acf'] ) ) {
		if ( isset( $data['acf']['my_field_name'] ) && ! empty( $data['acf']['my_field_name'] ) ) {
			$data['acf']['my_field_name'] = do_shortcode( $data['acf']['my_field_name'] );
		}
	}
	return $data;
}, 10, 3 );
```

:smile:

**Comment by brisa-pedronetto** [comment]
Thanks @airesvsg, that was exactly what I needed, cheers! :)

**Comment by airesvsg** [comment]
:laughing: :+1:
