### ISSUE TITLE
Getting ACF data for a set of posts?

### ISSUE THREAD

**Issue by andymerskin** [airesvsg/acf-to-wp-rest-api#4]
Hey there,

First off, thanks for creating this plugin. I think it will save me some time with custom post data.

From what I can tell, I can only request ACF data for a single post, given the ID, but not a group of posts. When I query my custom post type, I don't see any ACF data on the returned posts:
e.g. `/wp-json/wp/v2/projects`.

Right now, the only way to get everything is to request my `projects` and then fire off a single request for each project's ID to get its ACF data using `/wp-json/acf/post/<ID>`.

It'd be really great to have ACF data being appended to post / custom post responses with the key `acf` and all its data within. Am I missing something?

Thanks!

**Comment by airesvsg** [comment]
Hi @docmars,

Fixed.

Cheers
