### ISSUE TITLE
ACF not showing in Custom Post type

### ISSUE THREAD

**Issue by fabioquarantini** [airesvsg/acf-to-wp-rest-api#5]
Hello
Thanks for this great plugin.
I'm having trouble retrieving the acf fields in my cpt response.
Currently im making this call:
GET http://website.com/wp-json/v2/locals/<id>
the "acf" field is not displaying.

This is what I added in my functions.php

```
add_action( 'init', 'my_custom_post_type_rest_support', 25 );

function my_custom_post_type_rest_support() {
    global $wp_post_types;
    $post_type_name = 'locals';
    if( isset( $wp_post_types[ $post_type_name ] ) ) {
        $wp_post_types[$post_type_name]->show_in_rest = true;
        $wp_post_types[$post_type_name]->rest_base = $post_type_name;
        $wp_post_types[$post_type_name]->rest_controller_class = 'WP_REST_Posts_Controller';
    }
}
```

"acf" field is showing up only in posts but not in my CPT, any suggestion?

**Comment by lethalwire** [comment]
In order to get the ACF fields I'm currently using: http://site.dev/wp-json/acf/post/27, where 27 is the post ID.

**Comment by airesvsg** [comment]
Hi @fabioquarantini,

Try to access that url format:
http://website.com/wp-json/wp/v2/locals/

In my last commit, I have added support for custom post type: https://github.com/airesvsg/acf-to-wp-rest-api/commit/97f164684ccf539dd040b0d7323028c5b83f40b0

Thanks.

Cheers

**Comment by fabioquarantini** [comment]
Sorry i made a typo in my url.
GET http://website.com/wp-json/wp/v2/locals/id
Thanks

**Comment by airesvsg** [comment]
:smile: :+1:

**Comment by fabioquarantini** [comment]
I mean, i made a typo in this issue not in my application, my url is this:
 http://website.com/wp-json/wp/v2/locals/id
but "acf" is not showing.
I'm running the last update of your plugin and WP REST API

**Comment by airesvsg** [comment]
locals is a public custom post type?

**Comment by fabioquarantini** [comment]
Yes
```
'public'				=> true,
'has_archive'			=> true,
'exclude_from_search'	=> false,
'publicly_queryable'	=> true,
```

**Comment by airesvsg** [comment]
can you send your fles for me?
airesvsg@gmail.com

**Comment by airesvsg** [comment]
Hi @fabioquarantini,

try the steps below:
1- Access the permalinks settings ( **Settings** > **Permalinks** );
2- Click the **Save Changes** button.

**Comment by fabioquarantini** [comment]
The permalink doesn’t resolve the problem. I sent you the data.
Thanks

**Comment by airesvsg** [comment]
Hi @fabioquarantini,
I updated the plugin in your admin and the magic happened.
I sent screens for your e-mail with the responses.

**Comment by fabioquarantini** [comment]
Thanks :thumbsup:

**Comment by airesvsg** [comment]
:+1:
