### ISSUE TITLE
All request endpoints return null

### ISSUE THREAD

**Issue by jairgarcia** [airesvsg/acf-to-wp-rest-api#7]
When i make a request to the endpoints, all return null. For example:

$.ajax('http://localhost:3000/wp-json/acf/post/1').then( function( data ) {
    console.log( data );
})

in the console, return null

**Comment by airesvsg** [comment]
Hi @jairgarcia,

what are the versions?
**WordPress**: 
**WP REST API**:
**ACF to WP REST API**:

what you see when you access the url from the browser?

**Comment by jairgarcia** [comment]
Hi @airesvsg, thanks for the early response.

The versions are:

Wordpress: 4.4
WP REST API: 2.0
ACF to WP REST API: 1.2

I see the same response: null

Thanks.

**Comment by airesvsg** [comment]
Can you send your project for me?
airesvsg@gmail.com

The plugin does not require authentication.

**Comment by airesvsg** [comment]
Hi @jairgarcia,

Fixed https://github.com/airesvsg/acf-to-wp-rest-api/commit/e23ce066fa6dbeb12c54bc0fe5c75c7e139d2f65

Thanks
