### ISSUE TITLE
Request to page

### ISSUE THREAD

**Issue by jairgarcia** [airesvsg/acf-to-wp-rest-api#8]
**Hi, again.**

I have several questions:

**1.** When i request to a post that not exist, i show in the response the field of the unique post created.

http://prntscr.com/9iezns

**Note:** The post 8 not exist in the wordpress admin

**2.** When i tried make the request to the fields in a page not show nothing, how i must make a request for the fields in the pages?.

**3.** In the request to the options, in the response show this:

http://prntscr.com/9if1y3

The fields in **ACF** are configured like this:

http://prntscr.com/9if2lw

**Thanks for you help. I appreciate.**

**Comment by airesvsg** [comment]
Hi, again! :smile: 
could you send the database dump?

**3.** in your config they needs to have rule for **Options Page**.

![Options page](http://airesgoncalves.com.br/screenshot/acf-to-wp-rest-api/issues/8/options-page.png)

**Comment by airesvsg** [comment]
Hi @jairgarcia,

please, update your plugin and see if the error still happens.

**Comment by jairgarcia** [comment]
Hi **@airesvsg**,

Thanks for the new feature. I'll try and tell you.

Send Databases to your email.

**Comment by jairgarcia** [comment]
The issue **1** and **3** are ready. :+1:

**Comment by airesvsg** [comment]
**2.** Now you can get them by url:
`/wp-json/acf/page/{id}`
or when you list all pages:
`/wp-json/wp/v2/pages/`
or when you list an specific page:
`/wp-json/wp/v2/pages/{id}`

:+1:
