### ISSUE TITLE
Including Custom Post Types & Corresponding ACF Data

### ISSUE THREAD

**Issue by roti-dev** [airesvsg/acf-to-wp-rest-api#9]
Is there a way to include ACF fields from a custom post type ?

**Comment by airesvsg** [comment]
Hi @rotimi-dev,

**1.** you need to register the custom post type:
```PHP
function my_custom_post() {
  $args = array(
    'public' => true,
    'label' => 'Books',
  );  
  register_post_type( 'book', $args );
}
add_action( 'init', 'my_custom_post' );
```
**2.** Select your custom post type when you create the fields on acf:
![acf](http://airesgoncalves.com.br/screenshot/acf-to-wp-rest-api/issues/9/acf-custom-post-type.png)

**3.** You need to enable the custom post type in WP REST API
```PHP
function my_custom_post_type_rest_support() {
  global $wp_post_type;

  $wp_post_type['book']->show_in_rest = true;
  $wp_post_type['book']->rest_base = 'book';
  $wp_post_type['book']->rest_controller_class = 'WP_REST_Post_Controller';
}
add_action( 'init', 'my_custom_post_type_rest_support', 30 );
```

**4.** Now you can access via url:
`http://localhost/wp-json/acf/book/{id}`

or when you list via WP REST API endpoint:
`http://localhost/wp-json/wp/v2/book/`
`http://localhost/wp-json/wp/v2/book/{id}`

Cheers

**Comment by airesvsg** [comment]
Hi @rotimi-dev,

Please, replace the variable `$wp_post_type`in the function `my_custom_post_type_rest_support` to `$wp_post_types`.

```PHP
function my_custom_post_type_rest_support() {
  global $wp_post_types;

  $wp_post_types['book']->show_in_rest = true;
  $wp_post_types['book']->rest_base = 'book';
  $wp_post_types['book']->rest_controller_class = 'WP_REST_Post_Controller';
}
add_action( 'init', 'my_custom_post_type_rest_support', 30 );
```
